#!/bin/sh

###
# F.U.L.L.S.T.O.R.Y init script
#
# Copyright: (C) 2007-2008 Kel Modderman <kel@otaku42.de>
# Copyright: (C) 2008 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# License:   GPLv2
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# http://developer.berlios.de/projects/fullstory
###

PATH=/sbin:/usr/sbin:$PATH

# set default umask
umask 0022

# this is only invoked from fll-kde-desktop, inherit its environment
NAME="fll-xfce-desktop"

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -s /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

###
# read in variables from our default conffile
###
if [ -s "/etc/default/${NAME}" ]; then
	. "/etc/default/${NAME}"
fi

###
# read in variables from /etc/default/fll-locales
###
if [ -s /etc/default/fll-locales ]; then
	. /etc/default/fll-locales
fi

###
# cheatcode handling
###
for param in $(cat /proc/cmdline); do
	case "${param}" in
		flldebug=*)
			[ "${param#flldebug=}" = "${NAME}" ] && set -x
			;;
		nointro)
			NOINTRO="yes"
			;;
	esac
done

###
# set wallpaper defaults in desktop.xml
###
mkdir -p "${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml"
XFCE_DESKTOP_XML="${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"

# handle case where FLL_WALLPAPER is defined in kde4 directory syntax
# aptosid-art-wallpaper-* provides a symlink in /usr/share/wallpapers/ to common res wallpaper
if [ -d ${FLL_WALLPAPER} ]; then
	FLL_WALLPAPER=$(find $(dirname ${FLL_WALLPAPER}) -maxdepth 1 -type l -iname $(basename ${FLL_WALLPAPER}).*)
fi

if [ "${FLL_WALLPAPER}" ] && [ ! -f "${XFCE_DESKTOP_XML}" ]; then

	cat > "${XFCE_DESKTOP_XML}" << EOF
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-desktop" version="1.0">
  <property name="backdrop" type="empty">
    <property name="screen0" type="empty">
      <property name="monitor0" type="empty">
        <property name="image-path" type="string" value="${FLL_WALLPAPER}"/>
        <property name="image-style" type="int" value="3"/>
      </property>
    </property>
  </property>
</channel>
EOF
fi

###
# set desktop theme defaults in xsettings.xml (aptosid-$RELEASE theme)
###
mkdir -p "${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml"
XFCE_SETTINGS_XML="${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
# currently distro defaults does not provide the release codename var - use part of gfxboot name
XFCE_COLOURS="aptosid-${FLL_GFXBOOT_THEME#*-*-}"
if [ ! -f "${XFCE_SETTINGS_XML}" ] && [ ${XFCE_COLOURS} ]; then
	cat > "${XFCE_SETTINGS_XML}" << EOF
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xsettings" version="1.0">
  <property name="Net" type="empty">
    <property name="ThemeName" type="string" value="${XFCE_COLOURS}"/>
    <property name="IconThemeName" type="empty"/>
    <property name="DoubleClickTime" type="int" value="250"/>
    <property name="DoubleClickDistance" type="int" value="5"/>
    <property name="DndDragThreshold" type="int" value="8"/>
    <property name="CursorBlink" type="bool" value="true"/>
    <property name="CursorBlinkTime" type="int" value="1200"/>
    <property name="SoundThemeName" type="string" value="default"/>
    <property name="EnableEventSounds" type="bool" value="false"/>
    <property name="EnableInputFeedbackSounds" type="bool" value="false"/>
  </property>
  <property name="Xft" type="empty">
    <property name="DPI" type="empty"/>
    <property name="Antialias" type="int" value="-1"/>
    <property name="Hinting" type="int" value="-1"/>
    <property name="HintStyle" type="string" value="hintnone"/>
    <property name="RGBA" type="string" value="none"/>
  </property>
  <property name="Gtk" type="empty">
    <property name="CanChangeAccels" type="bool" value="false"/>
    <property name="ColorPalette" type="string" value="black:white:gray50:red:purple:blue:light blue:green:yellow:orange:lavender:brown:goldenrod4:dodger blue:pink:light green:gray10:gray30:gray75:gray90"/>
    <property name="FontName" type="string" value="Sans 10"/>
    <property name="IconSizes" type="string" value=""/>
    <property name="KeyThemeName" type="string" value=""/>
    <property name="ToolbarStyle" type="string" value="icons"/>
    <property name="ToolbarIconSize" type="int" value="3"/>
    <property name="IMPreeditStyle" type="string" value=""/>
    <property name="IMStatusStyle" type="string" value=""/>
    <property name="MenuImages" type="bool" value="true"/>
    <property name="ButtonImages" type="bool" value="true"/>
    <property name="MenuBarAccel" type="string" value="F10"/>
    <property name="CursorThemeName" type="string" value=""/>
    <property name="CursorThemeSize" type="int" value="0"/>
    <property name="IMModule" type="string" value=""/>
  </property>
</channel>
EOF
fi

###
# set panel defaults
###
mkdir -p "${HOME}/.config/xfce4/panel/"
if [ -d /usr/share/aptosid-settings-xfce ]; then
	cp -r /usr/share/aptosid-settings-xfce/xfce4 ${HOME}/.config
	sed -i -e s/FLL_LIVE_USER/${FLL_LIVE_USER}/ ${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
fi

###
# create .config/autostart dir
###
mkdir -p "${HOME}/.config/autostart"

###
# disable tips on startup
###
FLL_CONF_PRESEED="${HOME}/.config/autostart/xfce4-tips-autostart.desktop"
if grep -s -q '^Hidden=' "${FLL_CONF_PRESEED}"; then
	sed -i 's|^Hidden=.*|Hidden=true|' "${FLL_CONF_PRESEED}"
else
	cat > "${FLL_CONF_PRESEED}" <<EOF

[Desktop Entry]
Hidden=true

EOF
fi

###
# set xfce splash login theme
###
FLL_CONF_PRESEED="${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml"
if [ "${XFCE_SPLASH_THEME}" ]; then
	mkdir -p "${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml"

	if [ ! -f "${FLL_CONF_PRESEED}" ]; then
	        cat > "${FLL_CONF_PRESEED}" << EOF
<?xml version="1.0" encoding="UTF-8"?>
 
<channel name="xfce4-session" version="1.0">
  <property name="splash" type="empty">
    <property name="Engine" type="string" value="${XFCE_SPLASH_ENGINE}"/>
    <property name="engines" type="empty">
      <property name="balou" type="empty">
        <property name="Theme" type="string" value="${XFCE_SPLASH_THEME}"/>
      </property>
    </property>
  </property>
</channel>
EOF
	fi
fi

###
# take care of the trash can
###
mkdir -p "${HOME}/.local/share/Trash/info/" "${HOME}/.local/share/Trash/files/"

###
# scan for index.html in fll specific live mountpoint directories
###
for mntpnt in /fll/*; do
	if [ -d "${mntpnt}" ] && [ -f "${mntpnt}/index.html" ]; then
		INDEXFILE="${mntpnt}/index.html"
		for ext in svg png gif ico; do
			if [ -f "${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}" ]; then
				INDEXICON="${mntpnt}/${FLL_CDROM_INDEX_ICON}.${ext}"
				break
			fi
		done
		break
	fi
done

###
# create ~/Desktop if not present
###
mkdir -p "${HOME}/Desktop"

###
# create desktop shortcut to index.html
###
if [ -f "${INDEXFILE}"  ] && \
   [ ! -f "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" ]; then
	cat > "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" \
<<EOF
[Desktop Entry]
Encoding=UTF-8
Type=Application
Exec=x-www-browser ${INDEXFILE}
Icon=${INDEXICON}
Terminal=No
Name=${FLL_CDROM_INDEX}
GenericName=${FLL_CDROM_INDEX}
EOF

	if [ "${NOINTRO}" != "yes" ]; then
		ln -sf "${HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" \
			"${HOME}/.config/autostart/"
	fi
elif [ -e "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop" ]; then
	# toram + persistency
	rm -f "${HOME}/.config/autostart/${FLL_DISTRO_NAME}.desktop"
fi
