#!/bin/sh

# this is only invoked from fll-gnome-desktop, inherit its environment
NAME="fll-gnome-desktop"

if [ -s /etc/default/distro ]; then
	. /etc/default/distro
fi

###
# read in variables from our default conffile
###
if [ -s "/etc/default/${NAME}" ]; then
	. "/etc/default/${NAME}"
fi

gsettings set org.gnome.desktop.background picture-uri file://${FLL_WALLPAPER}.png
gsettings set org.gnome.desktop.background picture-options ${GDM_BACKGROUND_RENDERING_OPTION}
gsettings set org.gnome.shell.overrides button-layout ${WINDOWS_BUTTONS_LAYOUT}

rm ${HOME}/.config/autostart/background.desktop